# [theme.toml \| Yazi](https://yazi-rs.github.io/docs/configuration/theme/)

[tabs]
active = { fg = "black", bg = "blue" }
inactive = { fg = "blue", bg = "black" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "black", bg = "blue" }
normal_alt = { fg = "white", bg = "black" }
select_main = { fg = "black", bg = "blue" }
select_alt = { fg = "white", bg = "black" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "█", close = "█" }


[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[filetype]
rules = [
  # Special files
  { url = "*", is = "orphan", fg = "red" },
  { url = "*", is = "exec", fg = "green" },
  # Dummy files
  { url = "*", is = "dummy", fg = "red" },
  { url = "*/", is = "dummy", fg = "red" },
  # Fallback
  { url = "*", fg = "white" },
  { url = "*/", fg = "blue", bold = true },
]

[icon]
globs = []
dirs = []
files = []
exts = []
conds = []
